import Head from 'next/head'
import Header from '../components/header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>IMDB clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}  
      <Header/>


      {/* navbar */}
      <Navbar/>

      {/* result */}
      <Results/>
      
    </div>
  )
}
